// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ImvjAILCgz-Pp2QRgsF4N9d8Qoqo_bM',
    appId: '1:1082866843624:web:51f1d446c570ee80d3ee5d',
    messagingSenderId: '1082866843624',
    projectId: 'healthy-way-app-4bcab',
    authDomain: 'healthy-way-app-4bcab.firebaseapp.com',
    storageBucket: 'healthy-way-app-4bcab.appspot.com',
    measurementId: 'G-2EMYWSG4D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmGwTRNJz8wEoulEvdnOWbZHYSbg8bUFE',
    appId: '1:1082866843624:android:a35fa763854531efd3ee5d',
    messagingSenderId: '1082866843624',
    projectId: 'healthy-way-app-4bcab',
    storageBucket: 'healthy-way-app-4bcab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEqRogKGWA07YlrRprMtdLgYr6X7roLp4',
    appId: '1:1082866843624:ios:a829b0396388702cd3ee5d',
    messagingSenderId: '1082866843624',
    projectId: 'healthy-way-app-4bcab',
    storageBucket: 'healthy-way-app-4bcab.appspot.com',
    iosBundleId: 'com.example.flutterUntiteld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEqRogKGWA07YlrRprMtdLgYr6X7roLp4',
    appId: '1:1082866843624:ios:e35eb855e1d48b35d3ee5d',
    messagingSenderId: '1082866843624',
    projectId: 'healthy-way-app-4bcab',
    storageBucket: 'healthy-way-app-4bcab.appspot.com',
    iosBundleId: 'com.example.flutterUntiteld.RunnerTests',
  );
}
